from enum import StrEnum


class AuthErrorCode(StrEnum):
    USER_PASSWORD_MATCH = "USER_PASSWORD_MATCH"
    USER_PASSWORD_MISMATCH = "USER_PASSWORD_MISMATCH"
    INVALID_PASSWORD = "INVALID_PASSWORD"
    BAD_CREDENTIALS = "BAD_CREDENTIALS"
    BAD_TOKEN = "BAD_TOKEN"
    USER_ALREADY_VERIFIED = "USER_ALREADY_VERIFIED"
    USER_NOT_VERIFIED = "USER_NOT_VERIFIED"


class UserErrorCode(StrEnum):
    USER_ALREADY_EXIST = "USER_ALREADY_EXIST"
    USER_NOT_EXIST = "USER_NOT_EXIST"


class MailErrorCode(StrEnum):
    SEND_ERROR = "SEND_ERROR"
