"""alter_user_table

Revision ID: 0af44c273d96
Revises: d202363876d2
Create Date: 2024-10-15 11:51:11.253278

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0af44c273d96"
down_revision: Union[str, None] = "d202363876d2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("first_name", sa.String(length=50), nullable=False, comment="Имя"),
    )
    op.alter_column(
        "user",
        "email",
        existing_type=sa.VARCHAR(length=320),
        comment="Email адрес",
        existing_comment="Email адрес пользователя",
        existing_nullable=False,
    )
    op.alter_column(
        "user",
        "gender",
        existing_type=postgresql.ENUM("MALE", "FEMALE", name="gendertype"),
        comment="Пол пользователя",
        existing_nullable=False,
    )
    op.alter_column(
        "user",
        "hashed_password",
        existing_type=sa.VARCHAR(length=1024),
        comment="Захешированный пароль",
        existing_nullable=False,
    )
    op.alter_column(
        "user",
        "is_active",
        existing_type=sa.BOOLEAN(),
        comment="Активен?",
        existing_nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "user",
        "is_verified",
        existing_type=sa.BOOLEAN(),
        comment="Подтверждён?",
        existing_nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "user",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        comment="Создан",
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
    )
    op.alter_column(
        "user",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        comment="Изменён",
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        comment=None,
        existing_comment="Изменён",
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
    )
    op.alter_column(
        "user",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        comment=None,
        existing_comment="Создан",
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
    )
    op.alter_column(
        "user",
        "is_verified",
        existing_type=sa.BOOLEAN(),
        comment=None,
        existing_comment="Подтверждён?",
        existing_nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "user",
        "is_active",
        existing_type=sa.BOOLEAN(),
        comment=None,
        existing_comment="Активен?",
        existing_nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "user",
        "hashed_password",
        existing_type=sa.VARCHAR(length=1024),
        comment=None,
        existing_comment="Захешированный пароль",
        existing_nullable=False,
    )
    op.alter_column(
        "user",
        "gender",
        existing_type=postgresql.ENUM("MALE", "FEMALE", name="gendertype"),
        comment=None,
        existing_comment="Пол пользователя",
        existing_nullable=False,
    )
    op.alter_column(
        "user",
        "email",
        existing_type=sa.VARCHAR(length=320),
        comment="Email адрес пользователя",
        existing_comment="Email адрес",
        existing_nullable=False,
    )
    op.drop_column("user", "first_name")
    # ### end Alembic commands ###
